#pragma once  

namespace vrd {
    /** {zh}
    * 使用 RTS 作为业务服务器时需要
    * 上线正式服务时，需要在自己服务端部署
    */

    /** {en}
    * Required when using RTS as a business server
    * When the official service is launched, it needs to be deployed on its own server
    */
	static const std::string URL = "";

    /** {zh}
    * RTC 需要
    * 每个应用的唯一标识符，由 RTC 控制台申请获得，不同的 AppId 生成的实例在 RTC 中进行音视频通话完全独立，无法互通。
    *  https://console.volcengine.com/rtc/listRTC
    */

    /** {en}
    * Required when using RTC
    * The unique identifier of each application is obtained through the application of the RTC console. 
    * The instances generated by different AppIds are completely independent in the audio and video calls in RTC and cannot communicate with each other.
    * https://console.volcengine.com/rtc/listRTC
    */
    static const std::string APPID = "";

    /** {zh}
    * 使用 RTC 时需要，AppKey是用来生产rtc token及鉴权rtc token使用的。
    * https://console.volcengine.com/rtc/listRTC
    */

    /** {en}
    * When using RTC, AppKey is used to generate rtc token and authenticate rtc token
    * https://console.volcengine.com/rtc/listRTC
    */
    static const std::string APPKey= "";

    /** {zh}
    * 使用 RTS 时需要，用于服务端调用 RTS openapi 时鉴权使用。
    * 用来确认服务端有这个APPID的所有权 https://console.volcengine.com/iam/keymanage/
    */

    /** {en}
    * It is required when using RTS, and is used for authentication when the server calls RTS openapi.
    * Used to confirm that the server has the ownership of this APPID
    * https://console.volcengine.com/iam/keymanage/
    */
    static const std::string AccessKeyID = "";

    /** {zh}
    * 使用 RTS 时需要，用于服务端调用 RTS openapi 时鉴权使用。
    * 用来确认服务端有这个APPID的所有权 https://console.volcengine.com/iam/keymanage/
    */

    /** {en}
    * It is required when using RTS, and is used for authentication when the server calls RTS openapi.
    * Used to confirm that the server has the ownership of this APPID
    * https://console.volcengine.com/iam/keymanage/
    */
    static const std::string SecretAccessKey = "";

    /** {zh}
    * 火山控制台账户id, 使用会议和教育录制功能时需要。 https://console.volcengine.com/user/basics/
    */

    /** {en}
    * Volcano console account id, required to use meeting and educational recording features
    * https://console.volcengine.com/user/basics/
    */
    static const std::string AccountId= "";

    /** {zh}
    * 点播空间名, 使用会议和教育录制功能时需要。https://console.volcengine.com/vod/overview/
    */

    /** {en}
    * On-demand space name, required to use meeting and educational recording features.
    * https://console.volcengine.com/vod/overview/
    */
    static const std::string VodSpace = "";
}