source 'https://cdn.cocoapods.org/'
source 'https://github.com/volcengine/volcengine-specs.git'

# RTC SDK
pod 'VolcEngineRTC', '3.45.602'
pod 'VolcEngineRTC/ScreenCapture'

target 'veRTC_Demo' do
  platform :ios, '12.0'
  # 依赖 SDK
  # Depends on SDK
  pod 'Masonry'
  pod 'YYModel'
  pod 'AFNetworking', '~> 4.0'
  
  # 基础组件
  # Basic Component
  pod 'Core', :path => '../veRTC_Demo_iOS/Core'
  

  # 场景化源码
  # Scene source code
  # 登录
  pod 'Login', :path => '../veRTC_Demo_iOS/APP/Login'

  # 获取 RTS 登录信息
  pod 'JoinRTSParams', :path => '../veRTC_Demo_iOS/APP/JoinRTSParams'

  # 视频会议
  pod 'MeetingDemo', :path => '../veRTC_Demo_iOS/APP/MeetingDemo'
end

## 屏幕共享使用
target 'MeetingScreenShare' do
  platform :ios, '12.0'

end
